### PR TITLE
SRVLOGIC-202: Schedule apache-main sync from upstream

### PR DESCRIPTION
**Pull request by fantonangeli**
**Jira:**
https://issues.redhat.com/browse/SRVLOGIC-202

**IMPORTANT:**
Please read the jira comments.

**Description of the change:**
Set up a GitHub Action to sync our midstream main-apache branch with the upstream main branch every day.

This workflow will run every day at midnight to merge upstream/main to origin/main-apache.
The repository used to test this workflow is `fantonangeli/kogito-serverless-operator-fantonangeli-test`: 
https://github.com/fantonangeli/kogito-serverless-operator-fantonangeli-test/actions

**Motivation for the change:**
Keep our repository in sync with the upstream Apache repository.

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by fantonangeli** [comment]
Review request: @ricardozanini @rgdoliveira

**Review by ricardozanini — APPROVED** [review]
Great work! LGTM!

**Review by rgdoliveira — APPROVED** [review]
I think it looks good too.

@fantonangeli @ricardozanini I suppose we can merge this one and see it working and after that @fantonangeli can open this PR to the other repositories, WDYT?

**Comment by fantonangeli** [comment]
@ricardozanini @rgdoliveira 
Please note: to let the Sync CI run, we need to change the default branch to `main`

**Comment by rgdoliveira** [comment]
@fantonangeli I guess you have permissions to change the default branch to `main`, right?
If so, you can go ahead and change the default branch to `main` in all repos.

**Comment by fantonangeli** [comment]
> @fantonangeli I guess you have permissions to change the default branch to `main`, right? If so, you can go ahead and change the default branch to `main` in all repos.

I confirm I have the permissions, I can do it right now

**Review by rgdoliveira — APPROVED** [review]
LGTM

**Comment by fantonangeli** [comment]
> > @fantonangeli I guess you have permissions to change the default branch to `main`, right? If so, you can go ahead and change the default branch to `main` in all repos.
> 
> I confirm I have the permissions, I can do it right now
@rgdoliveira 
Ooops, I thought I had the permissions as per other repositories, but for this specific one, I cannot change the default branch. Can you please help?

**Comment by rgdoliveira** [comment]
> > Ooops, I thought I had the permissions as per other repositories, but for this specific one, I cannot change the default branch. Can you please help?

Done.

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
